import { describe, expect, it } from 'vitest';

import type {
  PptxDocument,
  PptxParseOptions,
} from '../../src/formats/pptx/types';
import type {
  PptxSceneDocument,
  PptxSceneSlide,
} from '../../src/formats/pptx/scene-types';
import {
  verifyPowerPointCreation,
  verifyPowerPointCreationWithParser,
} from '../../src/formats/pptx/writer/verify';

function emptySlide(key: string): PptxSceneSlide {
  return { elements: [], key };
}

function textSlide(key: string): PptxSceneSlide {
  return {
    elements: [
      {
        authored: {
          transform: { height: 40, width: 160, x: 10, y: 20 },
        },
        key: `${key}-text`,
        resolved: { hidden: false },
        text: {
          body: {},
          paragraphs: [
            {
              children: [{ key: `${key}-run`, text: 'Text', type: 'run' }],
              key: `${key}-paragraph`,
            },
          ],
        },
        type: 'text',
      },
    ],
    key,
  };
}

function scene(slides: PptxSceneSlide[]): PptxSceneDocument {
  return {
    layouts: [],
    masters: [],
    media: [],
    schemaVersion: 2,
    size: { height: 540, width: 960 },
    slides,
    themes: [],
  };
}

function generatedSlide(): PptxDocument['slides'][number] {
  return {
    elements: [],
    fill: { type: 'color', value: '#FFFFFF' },
    layoutElements: [],
    note: '',
  };
}

function document(slideCount: number): PptxDocument {
  return {
    size: { height: 540, width: 960 },
    slides: Array.from({ length: slideCount }, generatedSlide),
    themeColors: [],
    usedFonts: [],
  };
}

describe('PowerPoint creation verification', () => {
  it('passes the generated bytes and exact strict limits to the parser', async () => {
    const data = new Uint8Array([1, 2, 3]);
    const input = scene([emptySlide('slide-1')]);
    let receivedData: Uint8Array | undefined;
    let receivedOptions: PptxParseOptions | undefined;

    await verifyPowerPointCreationWithParser(data, input, (value, options) => {
      receivedData = value;
      receivedOptions = options;
      return Promise.resolve(document(1));
    });

    expect(receivedData).toBe(data);
    expect(receivedOptions).toEqual({
      audioMode: 'none',
      errorMode: 'strict',
      imageMode: 'none',
      limits: { maxEntries: 11, maxSlides: 1 },
      videoMode: 'none',
    });
  });

  it('uses a positive verification limit for a zero-slide package', async () => {
    let receivedOptions: PptxParseOptions | undefined;

    await verifyPowerPointCreationWithParser(
      new Uint8Array(),
      scene([]),
      (_value, options) => {
        receivedOptions = options;
        return Promise.resolve(document(0));
      },
    );

    expect(receivedOptions?.limits).toEqual({ maxEntries: 9, maxSlides: 1 });
  });

  it('rejects a different parsed slide count with exact evidence', async () => {
    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([emptySlide('slide-1')]),
        () => Promise.resolve(document(0)),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint slide count mismatch: expected 1, received 0',
      ),
    );
  });

  it('rejects an independently wrong generated width', async () => {
    const output = document(0);
    output.size.width = 959;

    await expect(
      verifyPowerPointCreationWithParser(new Uint8Array(), scene([]), () =>
        Promise.resolve(output),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint size mismatch: expected 960x540, received 959x540',
      ),
    );
  });

  it('rejects an independently wrong generated height', async () => {
    const output = document(0);
    output.size.height = 539;

    await expect(
      verifyPowerPointCreationWithParser(new Uint8Array(), scene([]), () =>
        Promise.resolve(output),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint size mismatch: expected 960x540, received 960x539',
      ),
    );
  });

  it('rejects a present slide with the wrong element count', async () => {
    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([textSlide('slide-1')]),
        () => Promise.resolve(document(1)),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint element count mismatch on slide 1: expected 1, received 0',
      ),
    );
  });

  it('identifies a missing generated slide at its one-based index', async () => {
    const output = document(2);
    output.slides = new Array<PptxDocument['slides'][number]>(2);
    output.slides[0] = generatedSlide();

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([emptySlide('slide-1'), emptySlide('slide-2')]),
        () => Promise.resolve(output),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint element count mismatch on slide 2: expected 0, received 0',
      ),
    );
  });

  it('uses the real strict parser at the production wrapper', async () => {
    await expect(
      verifyPowerPointCreation(new Uint8Array([1, 2, 3]), scene([])),
    ).rejects.toMatchObject({ name: 'PptxParseError' });
  });
});
