import { describe, expect, it } from 'vitest';

import type {
  PptxDocument,
  PptxParseOptions,
  Shape,
  Text,
} from '../../src/formats/pptx/types';
import type { PptxSvgRenderResult } from '../../src/formats/pptx/render-types';
import type {
  PptxSceneDocument,
  PptxSceneSlide,
} from '../../src/formats/pptx/scene-types';
import {
  verifyPowerPointCreation,
  verifyPowerPointCreationWithParser,
} from '../../src/formats/pptx/writer/verify';

function emptySlide(key: string): PptxSceneSlide {
  return { elements: [], key };
}

function textSlide(key: string): PptxSceneSlide {
  return {
    elements: [
      {
        authored: {
          transform: { height: 40, width: 160, x: 10, y: 20 },
        },
        key: `${key}-text`,
        resolved: { hidden: false },
        text: {
          body: {},
          paragraphs: [
            {
              children: [{ key: `${key}-run`, text: 'Text', type: 'run' }],
              key: `${key}-paragraph`,
            },
          ],
        },
        type: 'text',
      },
    ],
    key,
  };
}

function scene(slides: PptxSceneSlide[]): PptxSceneDocument {
  return {
    layouts: [],
    masters: [],
    media: [],
    schemaVersion: 2,
    size: { height: 540, width: 960 },
    slides,
    themes: [],
  };
}

function generatedSlide(): PptxDocument['slides'][number] {
  return {
    elements: [],
    fill: { type: 'color', value: '#FFFFFF' },
    layoutElements: [],
    note: '',
  };
}

function document(slideCount: number): PptxDocument {
  return {
    size: { height: 540, width: 960 },
    slides: Array.from({ length: slideCount }, generatedSlide),
    themeColors: [],
    usedFonts: [],
  };
}

function generatedText(text = 'Text'): Text {
  return {
    borderColor: '#000000',
    borderStrokeDasharray: '0',
    borderType: 'solid',
    borderWidth: 0,
    content: `<p><span>${text}</span></p>`,
    fill: null,
    height: 40,
    id: '2',
    isFlipH: false,
    isFlipV: false,
    isVertical: false,
    left: 10,
    name: 'Text Box 2',
    order: 0,
    rotate: 0,
    top: 20,
    type: 'text',
    vAlign: 'up',
    width: 160,
    wrap: true,
  };
}

function generatedShape(shapType: string, text = 'Text'): Shape {
  return {
    ...generatedText(text),
    shapType,
    type: 'shape',
  };
}

function rendered(documentValue: PptxDocument): PptxSvgRenderResult {
  return {
    slides: documentValue.slides.map((_slide, index) => ({
      data: new TextEncoder().encode(
        '<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg"></svg>',
      ),
      format: 'svg',
      height: documentValue.size.height,
      mimeType: 'image/svg+xml',
      slideNumber: index + 1,
      warnings: [],
      width: documentValue.size.width,
    })),
  };
}

describe('PowerPoint creation verification', () => {
  it('passes the generated bytes and exact strict limits to the parser', async () => {
    const data = new Uint8Array([1, 2, 3]);
    const input = scene([emptySlide('slide-1')]);
    let receivedData: Uint8Array | undefined;
    let receivedOptions: PptxParseOptions | undefined;
    let renderedDocument: PptxDocument | undefined;
    const parsed = document(1);

    await verifyPowerPointCreationWithParser(
      data,
      input,
      (value, options) => {
        receivedData = value;
        receivedOptions = options;
        return Promise.resolve(parsed);
      },
      (value) => {
        renderedDocument = value;
        return rendered(value);
      },
    );

    expect(receivedData).toBe(data);
    expect(receivedOptions).toEqual({
      audioMode: 'none',
      errorMode: 'strict',
      imageMode: 'none',
      limits: { maxEntries: 11, maxSlides: 1 },
      videoMode: 'none',
    });
    expect(renderedDocument).toBe(parsed);
  });

  it('verifies text and transform semantics before accepting a render', async () => {
    const output = document(1);
    const outputSlide = output.slides[0];
    if (outputSlide === undefined) throw new Error('Expected output slide');
    outputSlide.elements.push(generatedText());

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([textSlide('slide-1')]),
        () => Promise.resolve(output),
        rendered,
      ),
    ).resolves.toBeUndefined();
  });

  it('accepts only the authored non-rect text geometry', async () => {
    const inputSlide = textSlide('slide-1');
    const expected = inputSlide.elements[0];
    if (expected?.type !== 'text') throw new Error('Expected input text');
    expected.authored.geometry = 'roundRect';
    const output = document(1);
    const outputSlide = output.slides[0];
    if (outputSlide === undefined) throw new Error('Expected output slide');
    outputSlide.elements.push(generatedShape('roundRect'));

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([inputSlide]),
        () => Promise.resolve(output),
        rendered,
      ),
    ).resolves.toBeUndefined();

    outputSlide.elements = [generatedShape('ellipse')];
    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([inputSlide]),
        () => Promise.resolve(output),
        rendered,
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint text element missing at slide 1, element 1',
      ),
    );
  });

  it('rejects a generated text value that differs from the source scene', async () => {
    const output = document(1);
    const outputSlide = output.slides[0];
    if (outputSlide === undefined) throw new Error('Expected output slide');
    outputSlide.elements.push(generatedText('Wrong'));

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([textSlide('slide-1')]),
        () => Promise.resolve(output),
        rendered,
      ),
    ).rejects.toThrow(
      new Error('Generated PowerPoint text mismatch at slide 1, element 1'),
    );
  });

  it.each([
    ['x', { left: 11 }],
    ['y', { top: 21 }],
    ['width', { width: 161 }],
    ['height', { height: 41 }],
    ['rotation', { rotate: 1 }],
    ['horizontal flip', { isFlipH: true }],
    ['vertical flip', { isFlipV: true }],
  ])('rejects a generated transform with wrong %s', async (_name, change) => {
    const output = document(1);
    const outputSlide = output.slides[0];
    if (outputSlide === undefined) throw new Error('Expected output slide');
    const element = generatedText();
    Object.assign(element, change);
    outputSlide.elements.push(element);

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([textSlide('slide-1')]),
        () => Promise.resolve(output),
        rendered,
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint transform mismatch at slide 1, element 1',
      ),
    );
  });

  it('verifies run, break, and field text in source order', async () => {
    const inputSlide = textSlide('slide-1');
    const element = inputSlide.elements[0];
    if (element?.type !== 'text') throw new Error('Expected input text');
    const paragraph = element.text.paragraphs[0];
    if (paragraph === undefined) throw new Error('Expected input paragraph');
    paragraph.children = [
      { key: 'run', text: 'First', type: 'run' },
      { key: 'break', type: 'break' },
      { fieldType: 'slidenum', key: 'field', text: 'Second', type: 'field' },
    ];
    const output = document(1);
    const outputSlide = output.slides[0];
    if (outputSlide === undefined) throw new Error('Expected output slide');
    outputSlide.elements.push(generatedText('First<br>Second'));

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([inputSlide]),
        () => Promise.resolve(output),
        rendered,
      ),
    ).resolves.toBeUndefined();
  });

  it('verifies paragraph separators instead of concatenating paragraphs', async () => {
    const inputSlide = textSlide('slide-1');
    const element = inputSlide.elements[0];
    if (element?.type !== 'text') throw new Error('Expected input text');
    element.text.paragraphs.push({
      children: [{ key: 'second-run', text: 'More', type: 'run' }],
      key: 'second-paragraph',
    });
    const output = document(1);
    const outputSlide = output.slides[0];
    if (outputSlide === undefined) throw new Error('Expected output slide');
    const generated = generatedText();
    generated.content = '<p><span>Text</span></p><p><span>More</span></p>';
    outputSlide.elements.push(generated);

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([inputSlide]),
        () => Promise.resolve(output),
        rendered,
      ),
    ).resolves.toBeUndefined();
  });

  it('rejects a sparse generated text element with an exact location', async () => {
    const output = document(1);
    const outputSlide = output.slides[0];
    if (outputSlide === undefined) throw new Error('Expected output slide');
    outputSlide.elements = new Array<
      PptxDocument['slides'][number]['elements'][number]
    >(1);

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([textSlide('slide-1')]),
        () => Promise.resolve(output),
        rendered,
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint text element missing at slide 1, element 1',
      ),
    );
  });

  it('rejects a source text element without an authored transform', async () => {
    const inputSlide = textSlide('slide-1');
    const element = inputSlide.elements[0];
    if (element?.type !== 'text') throw new Error('Expected input text');
    delete element.authored.transform;
    const output = document(1);
    const outputSlide = output.slides[0];
    if (outputSlide === undefined) throw new Error('Expected output slide');
    outputSlide.elements.push(generatedText());

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([inputSlide]),
        () => Promise.resolve(output),
        rendered,
      ),
    ).rejects.toThrow(
      new Error(
        'Expected PowerPoint authored transform missing at slide 1, element 1',
      ),
    );
  });

  it('reports a non-text source element at its exact nested location', async () => {
    const inputSlide = textSlide('slide-2');
    inputSlide.elements.push({
      authored: {},
      feature: 'shape',
      key: 'unsupported',
      resolved: { hidden: false },
      type: 'unsupported',
    });
    const output = document(2);
    const outputSlide = output.slides[1];
    if (outputSlide === undefined) throw new Error('Expected output slide');
    outputSlide.elements.push(generatedText(), generatedText());

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([emptySlide('slide-1'), inputSlide]),
        () => Promise.resolve(output),
        rendered,
      ),
    ).rejects.toThrow(
      new Error(
        'Expected PowerPoint text element missing at slide 2, element 2',
      ),
    );
  });

  it('rejects a render that omits a generated slide', async () => {
    const output = document(1);

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([emptySlide('slide-1')]),
        () => Promise.resolve(output),
        () => ({ slides: [] }),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint render count mismatch: expected 1, received 0',
      ),
    );
  });

  it.each([
    ['wrong width', { width: 959 }],
    ['wrong height', { height: 539 }],
    ['wrong slide number', { slideNumber: 2 }],
    ['wrong MIME type', { mimeType: 'text/plain' }],
    ['wrong format', { format: 'png' }],
    ['empty bytes', { data: new Uint8Array() }],
  ])('rejects a render with %s', async (_name, replacement) => {
    const output = document(1);
    const result = rendered(output);
    const slide = result.slides[0];
    if (slide === undefined) throw new Error('Expected rendered slide');
    Object.assign(slide, replacement);

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([emptySlide('slide-1')]),
        () => Promise.resolve(output),
        () => result,
      ),
    ).rejects.toThrow(
      new Error('Generated PowerPoint visual invariant mismatch on slide 1'),
    );
  });

  it.each([
    '<svg><script/></svg>',
    '<svg><foreignObject/></svg>',
    '<svg><image href="http://example.test/image.png"/></svg>',
    '<svg><image href="https://example.test/image.png"/></svg>',
    '<svg><image href="blob:unsafe"/></svg>',
    '<svg><image src="file:///tmp/unsafe.png"/></svg>',
    'not svg',
  ])('rejects unsafe rendered source %j', async (source) => {
    const output = document(1);
    const result = rendered(output);
    const slide = result.slides[0];
    if (slide === undefined) throw new Error('Expected rendered slide');
    slide.data = new TextEncoder().encode(source);

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([emptySlide('slide-1')]),
        () => Promise.resolve(output),
        () => result,
      ),
    ).rejects.toThrow(
      new Error('Generated PowerPoint unsafe SVG output on slide 1'),
    );
  });

  it('accepts an SVG root without an XML declaration', async () => {
    const output = document(1);
    const result = rendered(output);
    const slide = result.slides[0];
    if (slide === undefined) throw new Error('Expected rendered slide');
    slide.data = new TextEncoder().encode(
      '<svg xmlns="http://www.w3.org/2000/svg"></svg>',
    );

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([emptySlide('slide-1')]),
        () => Promise.resolve(output),
        () => result,
      ),
    ).resolves.toBeUndefined();
  });

  it('rejects bytes before an otherwise valid SVG root', async () => {
    const output = document(1);
    const result = rendered(output);
    const slide = result.slides[0];
    if (slide === undefined) throw new Error('Expected rendered slide');
    slide.data = new TextEncoder().encode(
      'unsafe<svg xmlns="http://www.w3.org/2000/svg"></svg>',
    );

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([emptySlide('slide-1')]),
        () => Promise.resolve(output),
        () => result,
      ),
    ).rejects.toThrow(
      new Error('Generated PowerPoint unsafe SVG output on slide 1'),
    );
  });

  it('uses a positive verification limit for a zero-slide package', async () => {
    let receivedOptions: PptxParseOptions | undefined;

    await verifyPowerPointCreationWithParser(
      new Uint8Array(),
      scene([]),
      (_value, options) => {
        receivedOptions = options;
        return Promise.resolve(document(0));
      },
    );

    expect(receivedOptions?.limits).toEqual({ maxEntries: 9, maxSlides: 1 });
  });

  it('rejects a different parsed slide count with exact evidence', async () => {
    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([emptySlide('slide-1')]),
        () => Promise.resolve(document(0)),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint slide count mismatch: expected 1, received 0',
      ),
    );
  });

  it('rejects an independently wrong generated width', async () => {
    const output = document(0);
    output.size.width = 959;

    await expect(
      verifyPowerPointCreationWithParser(new Uint8Array(), scene([]), () =>
        Promise.resolve(output),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint size mismatch: expected 960x540, received 959x540',
      ),
    );
  });

  it('rejects an independently wrong generated height', async () => {
    const output = document(0);
    output.size.height = 539;

    await expect(
      verifyPowerPointCreationWithParser(new Uint8Array(), scene([]), () =>
        Promise.resolve(output),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint size mismatch: expected 960x540, received 960x539',
      ),
    );
  });

  it('rejects a present slide with the wrong element count', async () => {
    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([textSlide('slide-1')]),
        () => Promise.resolve(document(1)),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint element count mismatch on slide 1: expected 1, received 0',
      ),
    );
  });

  it('identifies a missing generated slide at its one-based index', async () => {
    const output = document(2);
    output.slides = new Array<PptxDocument['slides'][number]>(2);
    output.slides[0] = generatedSlide();

    await expect(
      verifyPowerPointCreationWithParser(
        new Uint8Array(),
        scene([emptySlide('slide-1'), emptySlide('slide-2')]),
        () => Promise.resolve(output),
      ),
    ).rejects.toThrow(
      new Error(
        'Generated PowerPoint element count mismatch on slide 2: expected 0, received 0',
      ),
    );
  });

  it('uses the real strict parser at the production wrapper', async () => {
    await expect(
      verifyPowerPointCreation(new Uint8Array([1, 2, 3]), scene([])),
    ).rejects.toMatchObject({ name: 'PptxParseError' });
  });
});
