export const mutatedFiles = [
  'src/cli/launch.ts',
  'src/cli/node-io.ts',
  'src/cli/run.ts',
  'src/common/archive/read-entry.ts',
  'src/common/binary/base64.ts',
  'src/common/media/media-type.ts',
  'src/common/numbers.ts',
  'src/common/ooxml/units.ts',
  'src/common/opc/part-uri.ts',
  'src/common/text/css.ts',
  'src/common/text/html.ts',
  'src/common/xml/normalize.ts',
  'src/common/xml/read-xml.ts',
  'src/common/xml/tree.ts',
  'src/common/xml/types.ts',
  'src/common/xml/validate.ts',
  'src/formats/pptx/creation-limits.ts',
  'src/formats/pptx/creation-resource-validation.ts',
  'src/formats/pptx/creator.ts',
  'src/formats/pptx/errors.ts',
  'src/formats/pptx/internal/animation.ts',
  'src/formats/pptx/internal/border.ts',
  'src/formats/pptx/internal/chart.ts',
  'src/formats/pptx/internal/color.ts',
  'src/formats/pptx/internal/custom-geometry-guide.ts',
  'src/formats/pptx/internal/diagram.ts',
  'src/formats/pptx/internal/fill.ts',
  'src/formats/pptx/internal/font-style.ts',
  'src/formats/pptx/internal/math.ts',
  'src/formats/pptx/internal/paragraph.ts',
  'src/formats/pptx/internal/position.ts',
  'src/formats/pptx/internal/resource-limits.ts',
  'src/formats/pptx/internal/scheme-color.ts',
  'src/formats/pptx/internal/shadow.ts',
  'src/formats/pptx/internal/shape-path.ts',
  'src/formats/pptx/internal/shape.ts',
  'src/formats/pptx/internal/table.ts',
  'src/formats/pptx/internal/text.ts',
  'src/formats/pptx/internal/text-insets.ts',
  'src/formats/pptx/internal/xml-reader.ts',
  'src/formats/pptx/parser.ts',
  'src/formats/pptx/roundtrip/canonical-json.ts',
  'src/formats/pptx/roundtrip/consistency.ts',
  'src/formats/pptx/roundtrip/data-tree.ts',
  'src/formats/pptx/roundtrip/digest.ts',
  'src/formats/pptx/roundtrip/preview.ts',
  'src/formats/pptx/roundtrip/read.ts',
  'src/formats/pptx/roundtrip/source.ts',
  'src/formats/pptx/roundtrip/validate.ts',
  'src/formats/pptx/roundtrip/write.ts',
  'src/formats/pptx/scene-validation.ts',
  'src/formats/pptx/write-error.ts',
  'src/formats/pptx/writer/archive.ts',
  'src/formats/pptx/writer/content-types.ts',
  'src/formats/pptx/writer/hierarchy.ts',
  'src/formats/pptx/writer/identifiers.ts',
  'src/formats/pptx/writer/package-relationships.ts',
  'src/formats/pptx/writer/paragraph.ts',
  'src/formats/pptx/writer/parts.ts',
  'src/formats/pptx/writer/presentation.ts',
  'src/formats/pptx/writer/relationships.ts',
  'src/formats/pptx/writer/slide.ts',
  'src/formats/pptx/writer/text-body.ts',
  'src/formats/pptx/writer/text-node.ts',
  'src/formats/pptx/writer/text-shape.ts',
  'src/formats/pptx/writer/theme.ts',
  'src/formats/pptx/writer/xml.ts',
  'src/formats/pptx/writer/units.ts',
  'src/formats/pptx/writer/verify.ts',
  'src/formats/xlsx/errors.ts',
  'src/formats/xlsx/internal/archive.ts',
  'src/formats/xlsx/internal/content-types.ts',
  'src/formats/xlsx/internal/package-identity.ts',
  'src/formats/xlsx/internal/part-reader.ts',
  'src/formats/xlsx/internal/relationships.ts',
  'src/formats/xlsx/internal/resource-limits.ts',
  'src/formats/xlsx/internal/workbook-discovery.ts',
  'src/formats/xlsx/internal/workbook-manifest.ts',
];

export const pendingMutationFiles = [];

export const excludedMutationFiles = [
  {
    file: 'src/cli.ts',
    reason:
      'Executable composition root that only binds process state to mutation-tested launch behavior.',
  },
  {
    file: 'src/common/index.ts',
    reason: 'Pure re-export barrel with no runtime decisions or values.',
  },
  {
    file: 'src/formats/pptx/internal/context.ts',
    reason: 'Compile-time-only parser context interfaces and type aliases.',
  },
  {
    file: 'src/formats/pptx/scene-types.ts',
    reason: 'Compile-time-only scene model interfaces and type aliases.',
  },
  {
    file: 'src/formats/pptx/roundtrip/types.ts',
    reason: 'Compile-time-only round-trip snapshot and option contracts.',
  },
  {
    file: 'src/formats/pptx/index.ts',
    reason:
      'Typed public delegation wrappers produce only compile-error mutants; parser behavior is mutation-tested at its implementation and public boundaries.',
  },
  {
    file: 'src/formats/pptx/types.ts',
    reason: 'Compile-time-only interfaces and type aliases.',
  },
  {
    file: 'src/formats/pptx/write-types.ts',
    reason: 'Compile-time-only writer result, report, and error contracts.',
  },
  {
    file: 'src/formats/xlsx/index.ts',
    reason:
      'Pure XLSX public re-export barrel with no runtime decisions or values.',
  },
  {
    file: 'src/formats/xlsx/types.ts',
    reason: 'Compile-time-only XLSX public interfaces and type aliases.',
  },
  {
    file: 'src/index.ts',
    reason: 'Pure public re-export barrel with no runtime decisions or values.',
  },
  {
    file: 'src/types/txml.d.ts',
    reason: 'Ambient dependency declaration with no emitted runtime code.',
  },
];
