export {
  parsePptx,
  parsePptxWithDiagnostics,
  PptxParseError,
} from './formats/pptx/index';
export type {
  PptxDocument,
  PptxDiagnostic,
  PptxDiagnosticCode,
  PptxErrorMode,
  PptxElement,
  PptxInput,
  PptxParseOptions,
  PptxParseResult,
  PptxResourceLimits,
  PptxSceneAuthoredElement,
  PptxSceneDocument,
  PptxSceneElement,
  PptxSceneElementBase,
  PptxSceneGroupTransform,
  PptxSceneLayout,
  PptxSceneMaster,
  PptxSceneParagraph,
  PptxSceneParagraphProperties,
  PptxScenePlaceholder,
  PptxSceneResolvedElement,
  PptxSceneRunProperties,
  PptxSceneSize,
  PptxSceneSlide,
  PptxSceneTextBody,
  PptxSceneTextBodyProperties,
  PptxSceneTextBreak,
  PptxSceneTextElement,
  PptxSceneTextField,
  PptxSceneTextNode,
  PptxSceneTextRun,
  PptxSceneTheme,
  PptxSceneTransform,
  PptxSceneUnsupportedElement,
  PptxSlide,
} from './formats/pptx/index';
